version: '2'
services:
    mosquitto:
        image: orbsmiv/mosquitto-rpi
        restart: always
        ports:
            - "1883:1883"
    ingestor:
        image: eamonford/ingestor
        restart: always
        depends_on:
            - postgres
            - mosquitto
            - influxdb
        environment:
            - MQTT_URL=tcp://mosquitto:1883
            - INFLUX_URL=http://influxdb:8086
            - POSTGRES_URL=jdbc:postgresql://postgres/postgres
            - POSTGRES_USERNAME=postgres
            - POSTGRES_PASSWORD=password
    analyzer:
        image: eamonford/analyzer
        restart: always
        depends_on:
            - influxdb
        environment:
            - INFLUX_URL=http://influxdb:8086
    dashboard:
        image: fg2it/grafana-armhf:v3.1.1
        restart: always
        depends_on:
            - influxdb
        ports:
            - "80:3000"
        environment:
            - VIRTUAL_HOST=localhost
    influxdb:
        image: influxdb
        restart: always
        ports:
            - "8086:8086"
            - "8083:8083"
        environment:
            - DB_NAME=dionysus_readings
            - DAYS_TO_RETAIN=30
    postgres:
        image: postgres
        restart: always
        environment:
          - POSTGRES_PASSWORD=password
        ports:
            - "5432:5432"
    irrigator:
        image: eamonford/irrigator
        depends_on:
            - postgres
        environment:
            - MQTT_HOST=mosquitto
            - PG_HOST=postgres
            - IRRIGATOR_MASTER=dozen_laser
            - POSTGRES_USERNAME=postgres
            - POSTGRES_PASSWORD=password